name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build --prod

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitLab Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_REGISTRY_USER }}
        password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: registry.gitlab.com/SeifeddineABIDI/Approbation-frontend:${{ github.sha }},registry.gitlab.com/SeifeddineABIDI/Approbation-frontend:latest

    - name: Checkout k8s-manifests repository
      uses: actions/checkout@v4
      with:
        repository: SeifeddineABIDI/k8s-manifests
        token: ${{ secrets.GITHUB_PAT }}
        path: k8s-manifests

    - name: Update image tag in k8s-manifests
      run: |
        sed -i 's|registry.gitlab.com/SeifeddineABIDI/Approbation-frontend:.*|registry.gitlab.com/SeifeddineABIDI/Approbation-frontend:${{ github.sha }}|' k8s-manifests/frontend/deployment.yaml
        cd k8s-manifests
        git config user.email "seifeddine.abidi@esprit.tn"
        git config user.name "seifeddineAbidi"
        git add .
        git commit -m "Update frontend image to ${{ github.sha }}"
        git push origin main