name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build --prod

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: seifeddineabidi
        password: dckr_pat_dLjdzfxcTryKbRrvUcB8E5e9p7A

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          seifeddineabidi/approbation-frontend:${{ github.sha }}
          seifeddineabidi/approbation-frontend:latest

    - name: Checkout k8s-manifests repository
      uses: actions/checkout@v4
      with:
        repository: seifeddineAbidi/k8s-manifests
        token: ${{ secrets.GITHUB_PAT }}
        path: k8s-manifests

    - name: Update image tag in k8s-manifests
      run: |
        sed -i "s|image: .*|image: seifeddineabidi/approbation-frontend:${{ github.sha }}|" k8s-manifests/frontend/deployment.yaml
        cd k8s-manifests
        git config user.email "seifeddine.abidi@esprit.tn"
        git config user.name "seifeddineAbidi"
        git add .
        git commit -m "Update frontend image to ${{ github.sha }}"
        git push origin main
