name: Frontend Pipeline

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
      
      - name: Build production app
        run: npm run build -- --configuration=production
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/approbation-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/approbation-frontend:latest
          
      - name: Update Kubernetes manifests
        uses: actions/checkout@v4
        with:
          repository: SeifeddineABIDI/k8s-manifests
          path: manifests
          token: ${{ secrets.GH_PAT }}
          
      - name: Update image tag
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/approbation-frontend:latest|" manifests/frontend/deployment.yaml
          cd manifests
          git config user.name "seifeddineAbidi"
          git config user.email "seifeddine.abidi@esprit.tn"
          git add .
          git commit -m "Update frontend image"
          git push